---

  - hosts: all
    become: true
    tasks:
      - name: Bu gorev, Ubuntu Apache & PHP Kutuphane yuklemesi ve apt packet indexini gunceller
        ansible.builtin.package:
          name:
            - "{{ apache_server }}"
            - "{{ php_lib }}"
          state: latest
          update_cache: yes
        when: ansible_distribution == "Ubuntu"

     
